project:
  type: website
  output-dir: docs

website:
  title: "Blue Shift nas eleições brasileiras"
  navbar:
    left:
      - href: index.qmd
        text: "Introdução"
      - href: usa.qmd
        text: "EUA"
      - href: br.qmd
        text: "Brasil"
      - href: about.qmd
        text: "Sobre"
      - href: ref.qmd
        text: "Referências"


format:
  html:
    theme: cosmo
    include-after:
      - scripts.js
    css: styles.css
    toc: true
    markdown:
      external-link: true

editor: visual

sidebar:
  contents: auto
